Adds Create separate CSS files per component section
emulsify-ds/documentation pull request #34
Opened 2021-11-01 18:23 UTC by thejimbirch

**Summary**

Adds a section that instructs on how to create separate CSS files per component

Per discussion in https://emulsify.slack.com/archives/C4605SM9V/p1635530239020600

2021-11-02 11:47 UTC, ModulesUnraveled requested changes

2021-11-02 11:47 UTC, ModulesUnraveled commented on details/webpack-and-build.md
> +glob.sync(`${webpackDir}/css/*js`).forEach((file) => {
I'm getting an error that `ReferenceError: webpackDir is not defined.` Is there a line missing here?

2021-11-02 14:46 UTC, ModulesUnraveled commented on details/webpack-and-build.md
> +glob.sync(`${webpackDir}/css/*js`).forEach((file) => {
I wonder if there's a difference in what version of Emulsify you are using, and the latest in `master`

2021-11-02 14:56 UTC, asipple1 commented on details/webpack-and-build.md
> +glob.sync(`${webpackDir}/css/*js`).forEach((file) => {
On line 6 I have the following for webpackDir
`const webpackDir = path.resolve(__dirname);`

2021-11-02 23:06 UTC, ModulesUnraveled requested changes

2021-11-02 23:06 UTC, ModulesUnraveled commented on details/webpack-and-build.md
> +```
```suggestion

1. In `webpack/plugins.js` change

```
const MiniCssExtractPlugin = new _MiniCssExtractPlugin({
  filename: 'style.css',
  chunkFilename: '[id].css',
});
```

To:

```
const MiniCssExtractPlugin = new _MiniCssExtractPlugin({
  filename: '[name].css',
  chunkFilename: '[id].css'
});
```
```

2021-11-02 23:06 UTC, ModulesUnraveled commented on details/webpack-and-build.md
> +* * * custom-css.js
```suggestion
2. In the webpack directory create a css directory with the following structure. (Each js file should import its own `<component>.scss` file. Look at `webpack/css.js` for an example.)

```
.
└──webpack
│  └──css
│     │   component-1.js
│     │   component-2.js
```

```

2021-11-02 23:06 UTC, ModulesUnraveled commented on details/webpack-and-build.md
> +```
```suggestion
3. In webpack.common.js replace

```
entries.css = path.resolve(webpackDir, 'css.js');
```

with

```
// CSS Files.
glob.sync(`${webpackDir}/css/*js`).forEach((file) => {
  const baseFileName = path.basename(file);
  const newfilePath = `css/${baseFileName.replace('.js', '')}`;
  entries[newfilePath] = file;
});
```
```

2021-11-02 23:06 UTC, ModulesUnraveled commented on details/webpack-and-build.md
> +4. Now you can create your own Drupal libraries in the Drupal theme to import the files where you need them.
```suggestion
4. Now you can define CSS files in your Drupal libraries only where you need them, just like you do with js.

5. Finally, Storybook only loads the main `styles.scss` file, by default. So make sure you add anything not globbed into that file to `.storybook/preview.js`.
```

2021-11-03 20:27 UTC, ModulesUnraveled approved these changes
Got the suggestions fixed!

2021-11-03 20:27 UTC, merged